language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "pypy3"
install:
  - pip install -U pip setuptools wheel
  - pip install Cython # slow
  - pip install numpy
  - pip install . --verbose --verbose --verbose
script: py.test
